name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: setup java-17
      run: sudo apt install openjdk-17-jre-headless -y
    - name: setup maven
      run: sudo apt install maven -y
    - name: build package
      run: mvn clean package -DskipTests
    - name: Build the Docker image
      run: docker build . -t boardgame-image:t2
  - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
